### ISSUE TITLE
Error while installing

### ISSUE THREAD

**Issue by towux** [PteroPackages/Pytero#9]
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/PteroPackages/Pytero
  Cloning https://github.com/PteroPackages/Pytero to /tmp/pip-req-build-yfi10fef
  Running command git clone --filter=blob:none --quiet https://github.com/PteroPackages/Pytero /tmp/pip-req-build-yfi10fef
  Resolved https://github.com/PteroPackages/Pytero to commit de38e1a648c2ec00f8843ee2bd04fc6d53d0a9d7
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [18 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-req-build-yfi10fef/setup.py", line 12, in <module>
          from pytero import __version__
        File "/tmp/pip-req-build-yfi10fef/pytero/__init__.py", line 13, in <module>
          from .app import PteroApp
        File "/tmp/pip-req-build-yfi10fef/pytero/app.py", line 12, in <module>
          from .node import Node
        File "/tmp/pip-req-build-yfi10fef/pytero/node.py", line 2, in <module>
          from .servers import AppServer
        File "/tmp/pip-req-build-yfi10fef/pytero/servers.py", line 2, in <module>
          from .types import _Http, Allocation, Container, Egg, FeatureLimits, Limits, \
        File "/tmp/pip-req-build-yfi10fef/pytero/types.py", line 40, in <module>
          class _Http:
        File "/tmp/pip-req-build-yfi10fef/pytero/types.py", line 43, in _Http
          _raw: Callable[[str, str, Any | None], Any]
      TypeError: unsupported operand type(s) for |: '_SpecialForm' and 'NoneType'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed
× Encountered error while generating package metadata.
╰─> See above for output.
note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by devnote-dev** [comment]
What version of Python are you using?

**Comment by towux** [comment]
> 

3.9

**Comment by devnote-dev** [comment]
I think pip may have missed something here — the minimum supported version is 3.10 so it shouldn't have even installed. Upgrading your Python install should fix this.
